### ISSUE TITLE
Allow greater access to the SmoothBursty rate limiter

### ISSUE THREAD

**Issue by wjam** [google/guava#1974] opened 2015-02-13 15:42 UTC
Create a method, such as `create(permitsPerSecond, maxBurst, timeUnit)` so that the full functionality of the `SmoothBursty` class can be utilised.

**Use case**
Use a `RateLimiter` when the rate is applied on a wider timescale than just a single second. An example of this would be the GitHub API which has a rate limit of 5,000 per hour.

**Comment by PhilippWendler** [comment] 2015-02-20 07:41
I guess this is a duplicate of #1707.

That being sad, I would also appreciate this being made available. We would like to limit sending out notification emails with something like a low hourly limit, but a burst size of 10-15 minutes.

**Comment by siderakis** [comment] 2016-03-05 18:40
+1

**Comment by AlexAtLeanPath** [comment] 2017-01-18 18:08
We need bursting as well.  Sad to have to reinvent the wheel

**Comment by uptimestar** [comment] 2017-11-26 22:40
Ping on this.

**Comment by gmunisifreddy** [comment] 2018-01-12 00:43
We recently switched from Guava to https://github.com/bbeck/token-bucket due to this issue. It helped us a lot to implement rate limiting with bursts.

**Comment by MrGraversen** [comment] 2018-11-15 09:45
also interested in this.

**Comment by gmethvin** [comment] 2018-12-11 19:02
We released a small library for this: https://mvnrepository.com/artifact/com.iterable/guava-bursty-rate-limiter/0.1.0

**Comment by nglorioso** [comment] 2019-07-24 17:50
Agreed with @PhilippWendler that this is a dup.

Duplicate of #1707

**Comment by nglorioso** [comment] 2019-07-24 17:50
Duplicate of #1707

**Closed by nglorioso** 2019-07-24 17:50 UTC
