### ISSUE TITLE
user-provided Ticker for RateLimiter

### ISSUE THREAD

**Issue by bdupras** [google/guava#3037] opened 2018-01-22 23:48 UTC
Internally, RateLimiter code can already take a provided SleepingStopWatch, which in turn can take a provided Ticker. The the Ticker instance used is hard coded one that reads from the system clock. 

I would like to supply my own time source, so it would be great to have a public `create` method that allows the caller to provide a customer Ticker. (Use-case: simulation environment with a time clock controlled by the sim, including ability to pause and fast-forward.)

If accepted, I can supply a PR for the code change if so desired.

**Comment by findepi** [comment] 2020-01-03 07:50
Another use-case, not mentioned in the issue description, is the ability to test code that uses `RateLimiter`.
Currently such needs need to `Thread.sleep`, which is obviously very far from ideal.

@cpovirk

**Comment by findepi** [comment] 2020-01-03 07:54
(Same request is also tracked by https://github.com/google/guava/issues/1774)

**Comment by netdpb** [comment] 2020-01-06 17:43
This is a duplicate of #1774. Closing this issue in favor of that one.

**Closed by netdpb** 2020-01-06 17:43 UTC
Labels: package=concurrent, status=duplicate, status=research, type=addition, type=enhancement
