### ISSUE TITLE
Add FluentIterable.from(E) or of(E)

### ISSUE THREAD

**Issue by stephenh** [google/guava#2149] opened 2015-09-04 01:28 UTC
I'd like to do FluentIterable.from("a").append(otherStrings);

Granted, I can do FluentIterable.from(newArrayList("a")).append(otherStrings), but seems like a vararg is reasonable to avoid the "newArrayList" boilerplate.

**Comment by cpovirk** [comment] 2015-09-09 11:57
Duplicate of #1070.

**Closed by cpovirk** 2015-09-09 11:57 UTC
Labels: status: duplicate
