### ISSUE TITLE
LoadingCache returning values that "expired" when setting expireAfterWrite to 0 for testing

### ISSUE THREAD

**Issue by kringol** [google/guava#2513] opened 2016-06-29 09:29 UTC
Seems caused by 
LocalCache.java

  boolean isExpired(ReferenceEntry<K, V> entry, long now) {
    checkNotNull(entry);
    if (expiresAfterAccess()
        && (now - entry.getAccessTime() >= expireAfterAccessNanos)) {
      return true;
    }
    if (expiresAfterWrite()
        && (now - entry.getWriteTime() >= expireAfterWriteNanos)) {
      return true;
    }
    return false;
  }

Since expireAfterWrite = 0

But method
expiresAfterWrite() is implemented like
boolean expiresAfterWrite() {
    return expireAfterWriteNanos > 0;
  }

It never performs the time check

**Comment by lowasser** [comment] 2016-06-29 19:18
Hmmm.  The docs of expireAfterWrite say 

   * <p>When {@code duration} is zero, this method hands off to {@link #maximumSize(long)
   * maximumSize}{@code (0)}, ignoring any otherwise-specificed maximum size or weight. This can be
   * useful in testing, or to disable caching temporarily without a code change.

This logic is implemented in CacheBuilder.getMaximumWeight().

Did you actually experimentally verify that the values are returned?  Or did you just guess that from the code?

**Comment by kringol** [comment] 2016-06-30 03:18
I observed that behaviour during some tests with the following cache
```java
private final LoadingCache<String, Optional<String>> someCache = CacheBuilder.newBuilder()
            .weigher(STRING_WEIGHER)
            .maximumWeight(20000)
            .expireAfterWrite(0, TimeUnit.SECONDS)
            .softValues()
            .build(new CacheLoader<String, Optional<String>>() {
                @Override
                public Optional<String> load(@NotNull final String s) throws Exception {
                    return loadCache(s);
                }
            });
```

Some previous tests loaded some values on the cache and a later test reading it was returning the actual value from the cache instead of invoking the "load" operation, even though the expireAfterWrite was set to 0.
Maybe I overlooked something. I will take a few more looks into it.

**Comment by ben-manes** [comment] 2016-07-01 17:25
I couldn't reproduce. Can you provide an isolated test case?

**Comment by cpovirk** [comment] 2019-07-24 23:35
Closing, but if anyone can reproduce this, please reopen.

**Closed by cpovirk** 2019-07-24 23:35 UTC
Labels: package=cache, type=defect

**Comment by ben-manes** [comment] 2019-07-24 23:40
@cpovirk the linked issue #2979 says it might be the cause of this and includes a test case.

**Comment by cpovirk** [comment] 2019-07-25 00:05
Ah, thank you, my mistake. Let's track it in #2979, then.
