### ISSUE TITLE
Implement Stopwatch.toString() under GWT

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2365] opened 2016-01-21 22:26 UTC
Not a high priority. I just feel a little bad that users there would get something like "com.google.common.base.Stopwatch@0xdeadbeef".

**Comment by mardibiase** [comment] 2016-02-28 10:13
Hello @cpovirk, I was trying to implement a speculative fix for this issue and make a pull request.

The issue that I am facing is that some classes are not present in this repository, while cloning `https://code.google.com/p/guava-libraries/` as in the [ContributorSetUp](https://github.com/google/guava/wiki/ContributorSetUp) page in the wiki has them.
This mismatch is an issue because I can't make a pull request on those files.

In detail, I was editing:

- `/guava-gwt/src-super/com/google/common/base/super/com/google/common/base/Stopwatch.java`
- `/guava-gwt/test-super/com/google/common/base/super/com/google/common/base/StopwatchTest.java`
- `/guava-gwt/test/com/google/common/base/StopwatchTest_gwt.java`

and the first two of these are missing.

Are these the right classes to edit? Can you help me in any way? 

Thanks

**Comment by cpovirk** [comment] 2016-03-01 18:52
@mardibiase

First, sorry: It looks like `ContributorSetUp` is out of date. I've filed https://github.com/google/guava/issues/2405 for us to update it.

Second, as a general rule, we try not to maintain parallel copies of our classes for GWT and server. [Sometimes](https://github.com/google/guava/tree/master/guava-gwt/src-super/com/google/common) we have to, but usually we just hide the platform-specific code behind a method in the an aptly named `Platform` class. You would create something like `Platform.stopwatchToString(Stopwatch)` with separate implementations in the [server](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Platform.java) and [GWT](https://github.com/google/guava/blob/master/guava-gwt/src-super/com/google/common/base/super/com/google/common/base/Platform.java) copies.

Alternatively, you could look for a way to implement `Stopwatch.toString` itself in a GWT-compatible way, maybe with some multiplication and rounding. We *might* even be to tolerate slightly changes in rounding in the output if it helps.

**Comment by qianqianzhu** [comment] 2016-03-02 23:13
@cpovirk Can you create a reproducible example of this issue?
>users there would get something like "com.google.common.base.Stopwatch@0xdeadbeef"

**Closed** 2016-04-01 17:02 UTC
Labels: package: base, platform: gwt, status: accepted, type: defect
