### ISSUE TITLE
add method in  class Maps

### ISSUE THREAD

**Issue by Qunzer** [google/guava#2512] opened 2016-06-29 06:46 UTC
just like method, 

```
 public static <K, V> ImmutableMap<K, V> uniqueIndex(Iterator<K> keys,
      Function<? super K, V> valueFunction) 
```

add a method with three parameters(Iterator object, Function keyFunction, Function valueFunction), for each object in Iterator, we use keyFunciont and valueFunciton to get key and value for map.

**Comment by Qunzer** [comment] 2016-06-29 08:06
for example：
public static <T, K, V> Map<K, V> uniqueIndex(Iterator<T> values, Function<T, K> keyFunction, Function<T, V> valueFunction) {
        checkNotNull(keyFunction);
        checkNotNull(valueFunction);
        ImmutableMap.Builder<K, V> builder = ImmutableMap.builder();
        while (values.hasNext()) {
            T value = values.next();
            builder.put(keyFunction.apply(value), valueFunction.apply(value));
        }
        return builder.build();
    }

**Comment by lowasser** [comment] 2016-06-29 18:33
More or less a duplicate of https://github.com/google/guava/issues/330 -- not exactly, but close enough.  It certainly seems to me like this is better done either a) imperatively or b) using the feature for exactly this in Java 8, `Stream.collect(toMap(keyFunction, valueFunction))`.  

I think we're inclined against adding more of these features that Java 8 does so much better when we're hard at work making Guava for Java 8 a thing.

**Closed** 2019-05-12 12:18 UTC
Labels: package=collect, type=addition
