### ISSUE TITLE
Interrogate for classes in the JDK

### ISSUE THREAD

**Issue by lmajano** [google/guava#6718] opened 2023-09-15 10:44 UTC
I am in need to get top level listings of class names of certain JDK packages as we are building a dynamic import system.

Basically, if I have `java.util.*` I need to be able to get at runtime the classes that are in the `java.util`  package.  Can guava accomplish this?

**Comment by netdpb** [comment] 2023-09-15 21:16
This is a better question for a forum like StackOverflow than here. Try using the `[guava]` tag.

You could try using Guava's [ClassPath.getTopLevelClasses(String)](https://github.com/google/guava/blob/master/guava/src/com/google/common/reflect/ClassPath.java#L172) method.

Closing as this is not a bug report or feature request.

**Closed by netdpb** 2023-09-15 21:16 UTC
