### ISSUE TITLE
OutOfMemoryError by com.google.common.reflect.ClassPath.from

### ISSUE THREAD

**Issue by zeroall** [google/guava#3520] opened 2019-06-29 06:39 UTC
Hi, When I used skywalking, an OutOfMemoryError occurred, which was thrown when I called the method com. google. common. reflection. ClassPath $DefaultScanner. scanDirectory. I submitted an issue to skywalking project, which is a link:

**Comment by zeroall** [comment] 2019-06-29 06:40
https://github.com/apache/skywalking/issues/2969

**Comment by wu-sheng** [comment] 2019-06-29 06:49
Hi

SkyWalking is simply using `classpath#getTopLevelClassesRecursive` scan all classes in classpath. It works perfectly in all I known environments including hundreds of end users and millions of JVM. 
But we just receive this OOM report.

Could you guide us on how to address the issue?

This is the code ref, https://github.com/apache/skywalking/blob/63fb961c0d1de02f053045c3bf80361ebd7bd58d/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/annotation/AnnotationScan.java#L42-L53

**Comment by zeroall** [comment] 2019-06-29 08:59
The reason for the problem was found. I scanned the entry of the scanDirectory of the ClassPath class with Arthas and found that it scanned the skywalking-ui directory, which contained a large number of nodeJS packages. ClassPath was too busy to work, so it caused OOM.

I'm sorry for the problem caused by the inadvertent introduction of redundant documents.




mbaight@foxmail.com
 
From: 吴晟 Wu Sheng
Date: 2019-06-29 14:51
To: google/guava
CC: zeroall; Author
Subject: Re: [google/guava] OutOfMemoryError by com.google.common.reflect.ClassPath.from (#3520)
Hi
SkyWalking is simply using classpath#getTopLevelClassesRecursive scan all classes in classpath. It works perfectly in all I known environments including hundreds of end users and millions of JVM.
But we just receive this OOM report.
Could you guide us on how to address the issue?
This is the code ref, https://github.com/apache/skywalking/blob/63fb961c0d1de02f053045c3bf80361ebd7bd58d/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/annotation/AnnotationScan.java#L42-L53

**Comment by zeroall** [comment] 2019-06-29 09:02
Before the problem arises, the directory structure is as follows:

drwxr-xr-x. 10 root root  170 6月  29 16:59 .
drwxr-xr-x. 14 root root  162 6月  29 16:58 ..
drwxr-xr-x.  8 root root  135 6月  29 16:04 agent
drwxr-xr-x.  2 root root  121 6月  29 16:04 bin
drwxr-xr-x.  2 root root  175 6月  29 16:04 config
-rw-r--r--.  1 root root  27K 6月  29 16:04 LICENSE
drwxr-xr-x.  3 root root 4.0K 6月  29 16:04 licenses
drwxr-xr-x.  2 root root   21 6月  29 16:04 logs
-rw-r--r--.  1 root root  29K 6月  29 16:04 NOTICE
drwxr-xr-x.  2 root root 8.0K 6月  29 16:49 oap-libs
-rw-r--r--.  1 root root 2.0K 6月  29 16:04 README.txt
drwxr-xr-x.  7 root root 4.0K 6月  29 16:05 skywalking-ui
drwxr-xr-x.  2 root root   53 6月  29 16:05 webapp

The skywalking-ui directory contains the following files:

-rw-r--r--.    1 root root  858 6月  29 16:05 babel.config.js
-rw-r--r--.    1 root root   33 6月  29 16:05 .browserslistrc
drwxr-xr-x.    5 root root   75 6月  29 16:04 dist
-rw-r--r--.    1 root root 1.4K 6月  29 16:05 Dockerfile
-rw-r--r--.    1 root root 1.3K 6月  29 16:05 Dockerfile-ci
-rw-r--r--.    1 root root 4.4K 6月  29 16:05 gulpfile.js
-rw-r--r--.    1 root root  12K 6月  29 16:05 LICENSE
-rw-r--r--.    1 root root 2.3K 6月  29 16:05 nginx.conf
drwxr-xr-x.    4 root root   53 6月  29 16:04 node
drwxr-xr-x. 1137 root root  80K 6月  29 16:05 node_modules
-rw-r--r--.    1 root root 1.1K 6月  29 16:05 package.json
-rw-r--r--.    1 root root 388K 6月  29 16:05 package-lock.json
-rw-r--r--.    1 root root  864 6月  29 16:05 postcss.config.js
drwxr-xr-x.    2 root root   43 6月  29 16:05 public
-rw-r--r--.    1 root root 2.0K 6月  29 16:05 README.md
-rw-r--r--.    1 root root 1.6K 6月  29 16:05 run.sh
drwxr-xr-x.    8 root root  199 6月  29 16:05 src
-rw-r--r--.    1 root root 1.5K 6月  29 16:05 tsconfig.json
-rw-r--r--.    1 root root 1.2K 6月  29 16:05 tslint.json
-rw-r--r--.    1 root root 1.3K 6月  29 16:05 vue.config.js




mbaight@foxmail.com
 
From: 吴晟 Wu Sheng
Date: 2019-06-29 14:51
To: google/guava
CC: zeroall; Author
Subject: Re: [google/guava] OutOfMemoryError by com.google.common.reflect.ClassPath.from (#3520)
Hi
SkyWalking is simply using classpath#getTopLevelClassesRecursive scan all classes in classpath. It works perfectly in all I known environments including hundreds of end users and millions of JVM.
But we just receive this OOM report.
Could you guide us on how to address the issue?
This is the code ref, https://github.com/apache/skywalking/blob/63fb961c0d1de02f053045c3bf80361ebd7bd58d/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/annotation/AnnotationScan.java#L42-L53

**Comment by zeroall** [comment] 2019-06-29 09:07
This is a summary of some information printed by Arthas:

ts=2019-06-29 17:04:36; [cost=0.56186ms] result=@Object[][
    @File[/usr/local/skywalking/skywalking-ui/node_modules/_@babel_types@7.4.4@@babel/types/lib/constants],
    @AppClassLoader[sun.misc.Launcher$AppClassLoader@4d7e1886],
    @String[skywalking-ui/node_modules/@vue/babel-preset-app/node_modules/@babel/plugin-syntax-jsx/node_modules/@babel/core/node_modules/@babel/helpers/node_modules/@babel/traverse/node_modules/@babel/helper-function-name/node_modules/@babel/template/node_modules/@babel/types/lib/constants/],
    @HashSet[isEmpty=false;size=28],
]
ts=2019-06-29 17:04:36; [cost=0.127028ms] result=@Object[][
    @File[/usr/local/skywalking/skywalking-ui/node_modules/_@babel_types@7.4.4@@babel/types/lib/converters],
    @AppClassLoader[sun.misc.Launcher$AppClassLoader@4d7e1886],
    @String[skywalking-ui/node_modules/@vue/babel-preset-app/node_modules/@babel/plugin-syntax-jsx/node_modules/@babel/core/node_modules/@babel/helpers/node_modules/@babel/traverse/node_modules/@babel/helper-function-name/node_modules/@babel/template/node_modules/@babel/types/lib/converters/],
    @HashSet[isEmpty=false;size=28],
]
ts=2019-06-29 17:04:36; [cost=0.129942ms] result=@Object[][
    @File[/usr/local/skywalking/skywalking-ui/node_modules/_@babel_types@7.4.4@@babel/types/lib/definitions],
    @AppClassLoader[sun.misc.Launcher$AppClassLoader@4d7e1886],
    @String[skywalking-ui/node_modules/@vue/babel-preset-app/node_modules/@babel/plugin-syntax-jsx/node_modules/@babel/core/node_modules/@babel/helpers/node_modules/@babel/traverse/node_modules/@babel/helper-function-name/node_modules/@babel/template/node_modules/@babel/types/lib/definitions/],
    @HashSet[isEmpty=false;size=28],
]
ts=2019-06-29 17:04:36; [cost=0.09251ms] result=@Object[][
    @File[/usr/local/skywalking/skywalking-ui/node_modules/_@babel_types@7.4.4@@babel/types/lib/modifications/flow],
    @AppClassLoader[sun.misc.Launcher$AppClassLoader@4d7e1886],
    @String[skywalking-ui/node_modules/@vue/babel-preset-app/node_modules/@babel/plugin-syntax-jsx/node_modules/@babel/core/node_modules/@babel/helpers/node_modules/@babel/traverse/node_modules/@babel/helper-function-name/node_modules/@babel/template/node_modules/@babel/types/lib/modifications/flow/],
    @HashSet[isEmpty=false;size=29],
]




mbaight@foxmail.com
 
From: 吴晟 Wu Sheng
Date: 2019-06-29 14:51
To: google/guava
CC: zeroall; Author
Subject: Re: [google/guava] OutOfMemoryError by com.google.common.reflect.ClassPath.from (#3520)
Hi
SkyWalking is simply using classpath#getTopLevelClassesRecursive scan all classes in classpath. It works perfectly in all I known environments including hundreds of end users and millions of JVM.
But we just receive this OOM report.
Could you guide us on how to address the issue?
This is the code ref, https://github.com/apache/skywalking/blob/63fb961c0d1de02f053045c3bf80361ebd7bd58d/oap-server/server-core/src/main/java/org/apache/skywalking/oap/server/core/annotation/AnnotationScan.java#L42-L53

**Comment by cgdecker** [comment] 2019-07-29 17:04
If you believe there's an issue with `ClassPath`, please clarify what the actual problem you're seeing is. What's the stack trace for the `OutOfMemoryError`?

If you can provide us with that we might have something to go on, but for now I'm going to close this issue because it's unclear to me what the problem is and it feels unlikely that the problem is with `ClassPath` itself.

**Closed by cgdecker** 2019-07-29 17:04 UTC

**Comment by wk849411933** [comment] 2023-03-22 15:08
I met the same problem,and i found in oap.log , it shows '三月 22, 2023 10:58:55 下午 com.google.common.reflect.ClassPath$DefaultScanner scanDirectory
警告: Cannot read directory /Users/wk/Library/Mail' . I don't kown why. so could you tell me how u solved it?tks a lot
