### ISSUE TITLE
Request to expose com.google.common.io.ByteStreams::toByteArray as public

### ISSUE THREAD

**Issue by mlmitch** [google/guava#3054] opened 2018-03-05 15:09 UTC
com.google.common.io.ByteStreams currently has this convenience method:
 `public static byte[] toByteArray(InputStream in) throws IOException`

It also has this overload of `toByteArray` with no access modifier:
`static byte[] toByteArray(InputStream in, int expectedSize) throws IOException`

I am requesting that this overload be made public.

My use case is data decompression via java.util.zip.InflaterInputStream where I know the decompressed size before decompression. Using the `toByteArray` overload with the `expectedSize` argument will save byte array allocations.

**Comment by cgdecker** [comment] 2018-03-12 18:23
Duplicate of #2616

**Closed by cgdecker** 2018-03-12 18:23 UTC
Labels: package=io, status=triaged, type=addition
