### ISSUE TITLE
RangeSet should provide a method to test for intersection with another RangeSet

### ISSUE THREAD

**Issue by holgerbrandl** [google/guava#5855] opened 2022-01-05 13:50 UTC
Currently, the user has decompose one of the sets and check the ranges for overlap with the other RangeSet. 

It would be better if guava could support this directly as in the following example:
```java
 RangeSet<Integer> rangeSetA = TreeRangeSet.create();
   rangeSet.add(Range.closed(1, 10));
   rangeSet.add(Range.closedOpen(11, 15)); 

 RangeSet<Integer> rangeSetB = TreeRangeSet.create();
   rangeSet.add(Range.closed(8, 12)); 
   rangeSet.add(Range.closedOpen(20, 30)); 

// missing method:
if(rangeSetA.intersects(rangeSetB)){
 // do something
}

```

**Comment by Stephan202** [comment] 2022-01-05 15:49
While using a different term ("overlaps" rather than than "intersects") this looks like a duplicate of #2094.

(But I'll use this opportunity to say that yes, this would be a very welcome addition; our code base contains several copies of the example implementation shown in #2094.)

**Closed** 2022-01-06 14:31 UTC
Labels: type=addition, package=collect, status=duplicate
