### ISSUE TITLE
Can add a Method that like js of "a||b||c||d" ?

### ISSUE THREAD

**Issue by cao19920425** [google/guava#2995] opened 2017-11-18 15:03 UTC
In Java,I have been distressed about how to write code that like js of "a||b||c||d" .
If there are only two values,use a==null?b:a is not bad.
But if you have more than two values, writing is as annoying as writing a previous loop without guava and jdk8.
I think it's an easy but powerful Method.

**Comment by perceptron8** [comment] 2017-11-18 16:16
Duplicate of #384?

**Comment by cao19920425** [comment] 2017-11-18 16:36
It likes so...
I know.

**Comment by cao19920425** [comment] 2017-11-18 16:37
It looks like.
I know.

**Closed** 2017-11-18 18:07 UTC
