### ISSUE TITLE
allow use of a weak hashmap in the EventBus for listeners

### ISSUE THREAD

**Issue by xenoterracide** [google/guava#2930] opened 2017-08-30 16:11 UTC
The EventBus currently requires you to unregister/manually garbage collect. Making it responsible for Listener lifecycles. We have a problem where we have to manually deregister in order to avoid memory leaks, but the only hooks for us to do this also create subtle bugs. What'd we'd really like is for listeners to be stored as weak keys, so if the listener could otherwise be garbage collected it would be. This way the eventbus can be "global" or "session" and you can have listeners that come and go. If you need persistent listeners you can use your DI system, whether that be Spring, Guice, etc.

https://github.com/bennidi/mbassador is an eventbus that works this way, and there is some consideration on switching to it on our part, but the long term stability of that project is questionable.

what I would suggest for backwards compatibility is storing the listeners in [your own cache](https://github.com/google/guava/wiki/CachesExplained#eviction), and then adding a constructor or static method that allows the creation of an eventbus with a custom `CacheBuilder` allowing us to say `CacheBuilder.weakKeys(...)` or whatever. It's possible you could go for much less flexible and simply make it a boolean or something.

**Comment by perceptron8** [comment] 2017-08-30 16:25
Duplicate of #807? See https://groups.google.com/forum/#!topic/guava-discuss/fEbuAmk2VFE also.

**Comment by xenoterracide** [comment] 2017-08-30 16:32
probably a dupe of #807, though I don't agree with the solution proposed there. The problem all comes down to having listeners that have a shorter lifecycle than the eventbus, and that don't have good hooks of their own to deregister.

**Comment by ronshapiro** [comment] 2019-08-08 10:27
Closing this in favor of the duplicate issue

**Closed by ronshapiro** 2019-08-08 10:27 UTC
Labels: package=eventbus, type=enhancement
