### ISSUE TITLE
JavaDoc file package-list 404s on GitHub Pages

### ISSUE THREAD

**Issue by tavianator** [google/guava#2361] opened 2016-01-15 18:00 UTC
E.g. https://google.github.io/guava/releases/19.0/api/docs/package-list gives a 404, despite https://github.com/google/guava/blob/gh-pages/_releases/19.0/api/docs/package-list existing.

This causes things like

```
1 warning
[WARNING] Javadoc Warnings
[WARNING] javadoc: warning - Error fetching URL: https://google.github.io/guava/releases/19.0/api/docs/
```

**Comment by cgdecker** [comment] 2016-02-04 22:14
Turns out this is a duplicate of #2096.

**Closed by cgdecker** 2016-02-04 22:14 UTC
Labels: package: general, status: accepted, type: documentation
