### ISSUE TITLE
GWT: error: cannot access com.google.common.collect.AbstractIterator

### ISSUE THREAD

**Issue by morbilli** [google/guava#2793] opened 2017-04-17 17:09 UTC
Hello.
Trying to compile my GWT (2.8.0) project by maven with dependency:
```
<dependency>
  <groupId>com.google.guava</groupId>
  <artifactId>guava-gwt</artifactId>
  <version>21.0</version>
</dependency>
```
and got the following:
```
[INFO] diagnostic C:\Users\user\.m2\repository\com\google\guava\guava-gwt\21.0\guava-gwt-21.0.jar(com/google/common/collect/Collections2.java):532: error: cannot access com.google.common.collect.AbstractIterator
  private static final class OrderedPermutationIterator<E> extends AbstractIterator<List<E>> {
                                                                   ^
  bad source file: C:\Users\user\.m2\repository\com\google\guava\guava-gwt\21.0\guava-gwt-21.0.jar(com/google/common/collect/AbstractIterator.java)
    file does not contain class com.google.common.collect.AbstractIterator
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
[ERROR] error on execute: error during compilation
...
[ERROR] Failed to execute goal org.bsc.maven:maven-processor-plugin:1.0.0:process (process) on project portal: Error executing: error during compilation -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.bsc.maven:maven-processor-plugin:1.0.0:process (process) on project portal: Error executing
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error executing
        at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:204)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.Exception: error during compilation
        at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.executeWithExceptionsHandled(AbstractAnnotationProcessorMojo.java:353)
        at org.bsc.maven.plugin.processor.AbstractAnnotationProcessorMojo.execute(AbstractAnnotationProcessorMojo.java:197)
        ... 22 more
```
Target JDK is 1.8.
I'll appreciate any help about that. Thanks.

**Comment by cpovirk** [comment] 2017-04-18 15:53
I wonder if there's any chance that the jar was corrupted during download. If you delete `.m2\repository\com\google\guava\guava-gwt\21.0` and let Maven download it again, does it work any better?

**Comment by morbilli** [comment] 2017-04-18 21:03
Hi @cpovirk, it does not work, furthermore with 20.0 version I see the same situation.

**Comment by cpovirk** [comment] 2017-04-18 21:08
Thanks. Are you able to provide a self-contained example that reproduces the problem? Unfortunately, my experience with Guava-GWT problems has been that I usually can't reproduce them unless someone hands me a project that I can run `mvn` on myself. Otherwise, I end up using different settings somewhere that fail to reproduce the problem :(

**Comment by morbilli** [comment] 2017-04-18 21:13
Ok I'll try to reproduce the problem with some GWT example and let you know. Thanks for help.

**Comment by kluever** [comment] 2017-07-06 20:05
Closing for now - please re-open if you are able to provide such an example.

**Closed by kluever** 2017-07-06 20:05 UTC
