### ISSUE TITLE
Add comparison operators to Ordering

### ISSUE THREAD

**Issue by rafalkrupinski** [google/guava#2346] opened 2016-01-01 10:12 UTC
Please consider adding following comparison operators to Ordering class:
- `eq(a,b)` as shortcut for `comparator.compare(a,b)==0`
- `nq(a,b)` as shortcut for `comparator.compare(a,b)!=0`
- `lt(a,b)` as shortcut for `comparator.compare(a,b)<0`
- `lte(a,b)` as shortcut for `comparator.compare(a,b)<=0`
- `gt(a,b)` as shortcut for `comparator.compare(a,b)>0`
- `gte(a,b)` as shortcut for `comparator.compare(a,b)>=0`

**Comment by cpovirk** [comment] 2016-01-04 17:00
Duplicate of #897.

**Closed by cpovirk** 2016-01-04 17:00 UTC
