### ISSUE TITLE
Why RateLimiter is still Beta

### ISSUE THREAD

**Issue by MrXionGe** [google/guava#3813] opened 2020-02-28 13:39 UTC
package: com.google.common.util.concurrent
class: RateLimiter
### So I wonder why RateLimiter has always been Beta.

**Comment by JakeWharton** [comment] 2020-02-28 13:41
Dupe of #2797

**Comment by MrXionGe** [comment] 2020-02-28 13:45
@JakeWharton 
It looks like we don't have an exact plan yet, do we?

**Closed** 2020-03-02 21:44 UTC
Labels: status=duplicate

**Comment by BEE-JN** [comment] 2022-10-17 07:11
RateLimiter is still be beta in 31.0, but it seems work fine.
