### ISSUE TITLE
Preconditions and Verify and custom exceptions

### ISSUE THREAD

**Issue by pnowy** [google/guava#3046] opened 2018-02-17 18:57 UTC
I've read the ConditionalFailuresExplained guidelines but from my perspective it would be useful to have an option to throw custom exception by `Preconditions` or `Verify`. I was thinking about something like that (with overrides methods supports formatting):

```
public static void check(final boolean expression, Supplier<? extends RuntimeException> exceptionToThrowSupplier) {
    if (!expression) {
        throw requireNonNull(exceptionToThrowSupplier).get();
    }
}
```
Do you consider that kind of methods in `Preconditions` or `Verify` - or additional similar class with support of checks with custom exceptions (provided lazy by supplier or eagerly).

I could prepare it if it is acceptable approach.

Thanks

**Comment by lowasser** [comment] 2018-02-17 19:32
This seems to be a duplicate of #1388.

**Comment by pnowy** [comment] 2018-02-18 15:28
I agree with previous discussion that Preconditions and Verify could be not the best place to add that kind of method. But in my opinion it would be good to consider additional class (or maybe Throwables but I'm not sure about that) with that kind of custom exception support.

**Comment by jhmanson** [comment] 2018-02-21 05:32
Perhaps best to take the conversation to that bug?

**Closed by jhmanson** 2018-02-21 05:32 UTC
Labels: package=base

**Comment by pnowy** [comment] 2018-02-21 08:30
Well it's hard to have any discussion if all tickets are closed ...

**Comment by jbduncan** [comment] 2018-02-21 10:29
Agreed. I think https://github.com/google/guava/issues/1388, the original issue, should be re-opened. :)
