### ISSUE TITLE
Remove @Beta from com.google.common.util.concurrent.RateLimiter

### ISSUE THREAD

**Issue by basilv** [google/guava#2797] opened 2017-04-21 21:59 UTC
I'd like RateLimiter to come out of Beta. It has been around since version 13.0

**Comment by cpovirk** [comment] 2017-04-26 18:21
We'll take a look. There are a number of things about it that we've hoped to eventually change, but it's hard to see when we would ever get around to them, so perhaps we should just finalize it.

**Comment by maiph** [comment] 2017-07-10 00:21
There is a TODO over at com.google.common.util.concurrent.RateLimiter.create

```java
/*
 * TODO(cpovirk): make SleepingStopwatch the last parameter throughout the class so that the
 * overloads follow the usual convention: Foo(int), Foo(int, SleepingStopwatch)
 */
@VisibleForTesting
static RateLimiter create(SleepingStopwatch stopwatch, double permitsPerSecond) {
  RateLimiter rateLimiter = new SmoothBursty(stopwatch, 1.0 /* maxBurstSeconds */);
  rateLimiter.setRate(permitsPerSecond);
  return rateLimiter;
}
```

Would you want a pull request to refactor this?

**Comment by cpovirk** [comment] 2017-07-10 14:52
Sure, thanks.

**Comment by stevedes77** [comment] 2018-10-04 02:44
I would also like this API to come out of Beta. Seeing that there hasn't been much activity in this API since this issue was filed, what is the path to getting the annotation removed?

**Comment by djagielo** [comment] 2019-04-26 14:21
I'd also be glad to see that out of Beta. Are there any still blocking TODOs? What are the plans?

**Comment by vpriesner** [comment] 2020-06-05 12:31
Any updates?
There seems to be one TODO left:

```
 * @author Dimitris Andreou
 * @since 13.0
 */
// TODO(user): switch to nano precision. A natural unit of cost is "bytes", and a micro precision
// would mean a maximum rate of "1MB/s", which might be small in some cases.
```

**Comment by joaquinfernandez131** [comment] 2021-05-19 18:00
Any updates on this?

**Comment by eamonnmcmanus** [comment] 2022-03-18 18:10
Duplicate of #5612. I'm closing in favour of that one since it has an assignee and this one doesn't.

**Closed by eamonnmcmanus** 2022-03-18 18:10 UTC
Labels: package=concurrent, status=triaged, type=other, P3, type=debeta
