### ISSUE TITLE
Support code points in CharMatcher

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2711] opened 2017-01-15 01:38 UTC
It would be nice if `CharMatcher` supported code points in addition to `char` to match characters outside of the `char` range.

I know it defeats the name, but then if the name or the `CharMatcher` API is that important, Maybe add a `CodePointMatcher` for this use case.

**Comment by cgdecker** [comment] 2019-07-30 20:48
I think this is basically a duplicate of #1075.

**Closed by cgdecker** 2019-07-30 20:48 UTC
Labels: P3, package=base, status=duplicate, type=addition
