### ISSUE TITLE
Guava 20  unresolved dependencies

### ISSUE THREAD

**Issue by swetha-nfinity** [google/guava#3091] opened 2018-03-28 07:55 UTC
We just upgraded our codebase to Guava 20 and deplyed into service mix . we  got error related to com.google.error prone
later included errorprone dependency , now we are getting below error
org.osgi.framework.BundleException: Unresolved constraint in bundle webid-import [222]: Unable to resolve 222.4: missing requirement [222.4] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.net)(version>=20.0.0)(!(version>=21.0.0)))
	at 

Note: we are included above dependancies as embeded dependancy in pom.xml
<Embed-Dependency>
							com.google.errorprone,
							com.google.guava,
						
						</Embed-Dependency>

**Comment by jbduncan** [comment] 2018-03-28 11:52
Hi @swetha-nfinity. I'm not on the Guava team myself, but on reading your issue, it's not clear to me what the problem is and how it can be reproduced.

Can you explain things further for us? Also do you have an [MVCE](https://stackoverflow.com/help/mcve) that you can share with us? :)

**Comment by netdpb** [comment] 2018-03-28 14:46
What version of Java are you using? Guava works with Java 9 only after release 23.1. Prior to that you may have errors.

**Comment by netdpb** [comment] 2018-03-29 13:18
It sounds like you have a dependency version problem, where some of your dependencies are themselves requiring differing versions of Guava. I'm not sure how to help you. It would take some looking at your build and Karaf configuration.

Guava 20.0 was released back in October 2016. We've made a fair number of changes since then, including updating Guava's build configuration. Maybe you could try a later release?

But in any case, I'm not sure we're in the right position to debug your build/runtime configuration, so I'm closing this issue. If you get to the point where you believe there is a bug with Guava's most recent release that prevents it from being used in certain environments, please either reopen this bug or file a new one.

**Closed by netdpb** 2018-03-29 13:18 UTC
