### ISSUE TITLE
Consider moving immutable support to its own module/jar 

### ISSUE THREAD

**Issue by burtonator** [google/guava#2689] opened 2016-12-19 22:02 UTC
I'm a BIG fan of immutables in Guava. ImmutableList, ImmutableMap, etc.

However, some packages might not want to swallow ALL of Guava just to provide immutable APIs.

Further, there are issues with Guava versioning.  

If we had a guava-immutable module that we can just depend on which ONLY had the immutable collection support this would solve that problem.

**Comment by dimo414** [comment] 2016-12-20 02:28
> Further, there are issues with Guava versioning.

What sort of issues are you referring to? How would splitting Guava up into numerous (presumably interdependent) packages make version-hell easier?

See also https://github.com/google/guava/issues/1087

**Comment by burtonator** [comment] 2016-12-20 02:34
The version conflict would be mitigated if guava-immutables package had a different version number.

guava-N could depend on any version of guava-immutables though.

We are on Guava 15 internally due to a broken dependency issue with another package (long story).

**Comment by ogregoire** [comment] 2016-12-20 11:49
What about [Proguard](https://github.com/google/guava/wiki/UsingProGuardWithGuava)?

**Comment by ronshapiro** [comment] 2017-09-14 00:10
As @dimo414 mentioned, this is a dupe of #1087

**Closed by ronshapiro** 2017-09-14 00:10 UTC
