### ISSUE TITLE
Why both method invoked？V20

### ISSUE THREAD

**Issue by chxiaowu** [google/guava#2768] opened 2017-03-23 06:00 UTC
`public class Consumer {

	@Subscribe
	public void test1(List<Event1> list) {
		System.out.println("in event 1 list...");

	}

	@Subscribe
	public void test2(List<Event2> list) {
		System.out.println("in event 2 list...");

	}
}`

`public class MainTest {

	public static void main(String[] args) {
		List<Event1> list = new ArrayList<>();
		list.add(new Event1());
		EventBus eventBus = new EventBus();

		Consumer consumer = new Consumer();
		eventBus.register(consumer);
		eventBus.post(list);
	}

}`

**Comment by perceptron8** [comment] 2017-03-23 06:22
https://docs.oracle.com/javase/tutorial/java/generics/erasure.html
https://docs.oracle.com/javase/tutorial/java/generics/genTypes.html

**Comment by perceptron8** [comment] 2017-03-23 06:36
This is a duplicate of #1431.

**Comment by chxiaowu** [comment] 2017-03-23 07:27
Thanks... 
shame on ......

**Closed** 2017-03-23 16:31 UTC
