### ISSUE TITLE
Release a Guava that supports+requires GWT 2.8.0 upon GWT release

### ISSUE THREAD

**Issue by cpovirk** [google/guava#1999] opened 2015-03-12 18:27 UTC
- @lowasser internal CL 88242480 wants to use `SimpleImmutableEntry`.
- Internal CL 86210805 can be rolled back to use `AssertionError(String, Throwable)`.
- @kak internal CL 83767705 wanted to use `Arrays.copyOf`.
- My internal CL 59647656 wants to remove `AbstractIteratorTester` workarounds for bugs in `java.util` classes fixed in new releases of GWT.

GWT 2.7.0 was released in November. But note that we had bug reports from users of GWT 2.5.1 as late as October 2014, 9 months after the release of 2.6.0. We should get some idea of how quickly external users update the version of GWT they use.

**Comment by cpovirk** [comment] 2015-03-24 16:06
Note that `AssertionError(String, Throwable)` is not part of Java 6. We'll have to decide how important it is. As noted in #2012, we theoretically don't care about the version of Java required to *build* Guava, only that required to *run* it. However, we might benefit from Java 6 compatibility in our tests, since it could make them easier to run on Android.

**Comment by filip26** [comment] 2015-05-12 21:48
@cpovirk Guava compiled with GWT 2.6.1 dependency cannot be used by gwt.-maven-plugin 2.7.0 Any idea when GWT 2.7.0 will be supported? Thank you

**Comment by kluever** [comment] 2015-05-26 17:32
FYI, trying to bump our pom from 2.6.1 to 2.7.0 gives me the following error:

[ERROR] Plugin org.codehaus.mojo:gwt-maven-plugin:2.7.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:gwt-maven-plugin:jar:2.7.0: The repository system is offline but the artifact org.codehaus.mojo:gwt-maven-plugin:pom:2.7.0 is not available in the local repository. -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.codehaus.mojo:gwt-maven-plugin:2.7.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.codehaus.mojo:gwt-maven-plugin:jar:2.7.0

Am I missing something?

**Comment by cpovirk** [comment] 2015-05-26 17:45
That's an error we get internally only. We have Maven set up not to download anything, relying completely on a set of dependencies we downloaded in advance. The error is telling us that one of the needed dependencies wasn't pre-downloaded. You should be able to fix it by running our `update_maven_local_repository.sh` script.

I'll try to look into this problem now. I was surprised at the report that people can't use 2.7.0 if we use 2.6.1. (Thanks for letting us know.)

**Comment by cpovirk** [comment] 2015-05-26 19:05
- We'd like to remove our GWT-specific version of `Sets.newSetFromMap`.

**Comment by cpovirk** [comment] 2015-05-26 19:22
@filip26, can you let us know what errors you're seeing when using Guava with `gwt-maven-plugin` 2.7.0? [The first `guava-gwt`-using project I found on Github](https://github.com/xose/gwt-persona) continues to work fine if I change it to use `gwt-maven-plugin` 2.7.0.

**Comment by cpovirk** [comment] 2015-05-28 17:31
To figure out how many users we'd cut off if we required 2.7.0, I [asked on StackOverflow](http://stackoverflow.com/q/30493893/28465). The answer: A survey taken [at the end of November](http://grokbase.com/p/gg/google-web-toolkit/14bvw19n6f/future-of-gwt-study), about [a week after 2.7.0 was released](http://www.gwtproject.org/versions.html), had 35% of users using the new version (or HEAD). Look at all versions released within the past year, and the number rises to >80%. The ">80%" trend held for the two previous surveys, too: Within a year of a version's release, >80% of users are using it. That would give us 6 months until GWT 2.7.0 is at 80%. I think that would be a reasonable time to pull the trigger (barring developments in the reports that we're currently cutting off users of 2.7.0).

**Comment by cpovirk** [comment] 2015-07-27 18:07
(Internally, I've put together CL 99196888 for `newSetFromMap`.)

**Comment by cpovirk** [comment] 2015-07-30 14:53
- One (soon to be two) of our `GwtPlatform` classes would like to use `Arrays.copyOf`. Instead, they have to use `copyOfRange`.

**Comment by cpovirk** [comment] 2015-09-18 20:10
- Use `String.getBytes(Charset)`, as discussed in #2124.

**Comment by cpovirk** [comment] 2015-09-22 21:13
- Update our internal "Guava JDK6 compatibility" doc to reflect the new version of GWT.

**Comment by cpovirk** [comment] 2015-10-23 12:30
- Note in the release notes that we will no longer support Dev Mode: https://github.com/gwtproject/gwt/issues/9206#issuecomment-150033463

**Comment by cpovirk** [comment] 2015-10-23 12:34
(retitled to reflect that we're going straight to GWT 2.8.0 when available)

**Comment by cpovirk** [comment] 2015-10-23 17:24
I was asked internally whether it's possible to release a Guava compatible with both GWT pre-2.8.0 and GWT 2.8.0. I said:

> This requires both the double rollbacks http://cl/98113442 http://cl/100051360 and also some kind of plan for Charset: http://cl/99780060 Guava 19 and lower has its own copy of Charset, which will conflict with the copy GWT is adding in 2.8.0. I don't know of any way to avoid that problem.

But maybe someone can find one.

**Comment by spirylics** [comment] 2016-01-04 16:07
For information, I have try guava 20.0-SNAPSHOT with gwt 2.8-beta1.
it works fine with a full compilation but not with dev mode and super dev mode ; I have this exception : 

```java
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:130)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transform(GenerateJavaScriptAST.java:2515)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformExpressionStatement(GenerateJavaScriptAST.java:695)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformExpressionStatement(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:730)
[INFO]  at com.google.gwt.dev.jjs.ast.JExpressionStatement.traverse(JExpressionStatement.java:41)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transformIntoExcludingNulls(JTransformer.java:1076)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformBlock(GenerateJavaScriptAST.java:578)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformBlock(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:622)
[INFO]  at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:91)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transform(GenerateJavaScriptAST.java:2523)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodBody(GenerateJavaScriptAST.java:812)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodBody(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:829)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:81)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethod(GenerateJavaScriptAST.java:787)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.generatePrototypeDefinitions(GenerateJavaScriptAST.java:2330)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.generateTypeSetup(GenerateJavaScriptAST.java:1833)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformDeclaredType(GenerateJavaScriptAST.java:641)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformDeclaredType(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transformClassType(JTransformer.java:95)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:670)
[INFO]  at com.google.gwt.dev.jjs.ast.JClassType.traverse(JClassType.java:140)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformProgram(GenerateJavaScriptAST.java:1202)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformProgram(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:918)
[INFO]  at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1252)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:122)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer.transform(JTransformer.java:1056)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST.execImpl(GenerateJavaScriptAST.java:3014)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST.exec(GenerateJavaScriptAST.java:2795)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:378)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO]  at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO]  at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO]  at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO]  at java.lang.Thread.run(Thread.java:745)
[INFO] Caused by: java.lang.NullPointerException
[INFO]  at com.google.gwt.dev.jjs.ast.JMethod.getQualifiedJsName(JMethod.java:118)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.createStaticReference(GenerateJavaScriptAST.java:1707)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.dispatchToStatic(GenerateJavaScriptAST.java:886)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodCall(GenerateJavaScriptAST.java:874)
[INFO]  at com.google.gwt.dev.jjs.impl.GenerateJavaScriptAST$GenerateJavaScriptTransformer.transformMethodCall(GenerateJavaScriptAST.java:514)
[INFO]  at com.google.gwt.dev.jjs.ast.JTransformer$JRewriterVisitor.visit(JTransformer.java:835)
[INFO]  at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:246)
[INFO]  at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:127)
[INFO]  ... 52 more
[INFO]                [ERROR] at MapMaker.java(116): MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis))
[INFO]                   com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]                [ERROR] at MapMaker.java(116): MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis))
[INFO]                   com.google.gwt.dev.jjs.ast.JExpressionStatement
[INFO]                [ERROR] at MapMaker.java(107): {
[INFO]   MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis));
[INFO] }
[INFO]                   com.google.gwt.dev.jjs.ast.JBlock
[INFO]                [ERROR] at MapMaker.java(107): {
[INFO]   MapMaker$ExpiringComputingMap.setTimeout(new MapMaker$ExpiringComputingMap$1(this, key, value), LongLib.toInt(this.expirationMillis));
[INFO] }
[INFO]                   com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]                [ERROR] at MapMaker.java(42): com.google.common.collect.MapMaker$ExpiringComputingMap (extends LinkedHashMap implements ConcurrentMap)
[INFO]                   com.google.gwt.dev.jjs.ast.JClassType
[INFO]                [ERROR] at Unknown(0): <JProgram>
[INFO]                   com.google.gwt.dev.jjs.ast.JProgram
[INFO]             [ERROR] Unrecoverable exception, shutting down
[INFO] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[INFO]  at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:459)
[INFO]  at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.compilePermutation(JavaToJavaScriptCompiler.java:272)
[INFO]  at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:198)
[INFO]  at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
[INFO]  at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
[INFO]  at java.lang.Thread.run(Thread.java:745)
[INFO]             [ERROR] Not all permutation were compiled , completed (0/1)
```

Someone knows when guava 20 will be released ?

**Comment by cpovirk** [comment] 2016-01-04 17:14
Can you also report this to GWT? I would have hoped that our 20.0-SNAPSHOT would work with GWT 2.8.

**Comment by spirylics** [comment] 2016-01-04 17:39
Yes : https://github.com/gwtproject/gwt/issues/9259

**Comment by cpovirk** [comment] 2016-01-07 19:35
I think I have CLs out or submitted for all the points mentioned above, aside from Louis's CL 88242480, which I've told him should now be safe to submit.

**Comment by spirylics** [comment] 2016-01-12 09:06
About exception in my last comment, the error is caused by jsinteropmode. I have forgotten to drop this config. Last guava snapshot seems to be functionnal with gwt 2.8. When can we hope a release ?
Thanks

**Comment by cpovirk** [comment] 2016-01-14 16:55
Because Guava 19 may have problems with GWT 2.8, we're hoping to release Guava 20 shortly after the GWT release.

I think so, anyway. @cgdecker?

Hmm, maybe we should get a release candidate out so that we're able to promote to final faster?

**Comment by MikeN123** [comment] 2016-09-02 14:34
Are there any plans to release an RC? GWT 2.8 is just around the corner (RC2 was recently released), and due to a Guava dependency I'm unable to upgrade/test the new version at the moment (well, I'll give a try with a snapshot, but an RC or final release would be nicer).

**Comment by cgdecker** [comment] 2016-10-06 21:13
20.0-rc1, out now-ish, supports/requires GWT 2.8.0.

**Closed by cgdecker** 2016-10-06 21:13 UTC
Labels: package: general, platform: gwt, status: fixed, type: dev
