### ISSUE TITLE
provide Bazel BUILD support?

### ISSUE THREAD

**Issue by perezd** [google/guava#3017] opened 2017-12-23 17:25 UTC
It'd be nice for users who want to rely on this git repo directly as a bazel target. I've got it working already, its pretty trivial. Only question is should the tests run in bazel too (mirrored) or just leave that as is.

I'd be happy to contribute this, not sure what the right way to do that would be. Some Google projects have a separate "master-with-bazel" branch, others just have it inlined with pom.xml files. I'm flexible, how can I help?

**Comment by jbduncan** [comment] 2017-12-23 17:35
Possible duplicate of https://github.com/google/guava/issues/2850?

I wonder if it's even worth maintaining a Maven pom.xml and a Bazel BUILD at the same time. From what I've observed of other Google projects, it is difficult to maintain both kinds of files at the same time and can easily lead to them being out of sync. Thus I believe that it's best to wait until Bazel hits an LTS version and fully supports Windows, macOS and Linux, and migrate to Bazel then, as I argue in the linked issue above.

**Comment by jbduncan** [comment] 2017-12-23 17:37
Oh, actually, I think this issue could be made a sub-issue of #2850, rather than declaring it as a dupe. It seems to me that the task of creating a BUILD should be a sub-task of an overall Maven-to-Bazel migration.

**Comment by jbduncan** [comment] 2017-12-23 17:42
> ...Thus I believe that it's best to wait until Bazel hits an LTS version and fully supports Windows, macOS and Linux, and migrate to Bazel then, as I argue in the linked issue above.

But having said this, I'd be very happy to be proven otherwise, as my knowledge of Bazel is admittedly both very limited and not so current, so it's seems likely that my knowledge about keeping pom.xmls and BUILDs in sync is at least a bit out-of-date.

**Comment by ronshapiro** [comment] 2017-12-28 01:34
Let's continue on the linked issue - I think we would definitely support both maven and bazel as we migrated from one to the other.

**Closed by ronshapiro** 2017-12-28 01:34 UTC
