### ISSUE TITLE
FileBackedOutputStream failing to write with system account on windows

### ISSUE THREAD

**Issue by thebluemountain** [google/guava#6750] opened 2023-10-06 09:07 UTC
hi,

checking at CVE for an application, we are upgrading project dependencies.
among them, the application is using the guava library, 31.1-jre.

testing with the guava 32.0.1-jre on windows 2K12R2 with jdk 11.0.16.1, the FileBackedOutputStream failed to write when size exceeds the supplied threshold and the current user's account is the 'local system'

looking a bit further at the error, i see the error is occurring in the FileBackedOutputStream.update () method , when creating a new FileOutputStream from the temporary file created by the TempFileCreator.JavaNioCreator.createTempFile () method.

I created a test program to reproduce the error when running on windows 2K12R2 with 'local system' account.

It seems we can avoid this issue by using the Files.copy (InputStream, Path, CopyOption) to transfer the content of the memory buffer to the temporary file.

[guava-issue.zip](https://github.com/google/guava/files/12829118/guava-issue.zip)

attached is a log of the error and the source of sample program (Main.java) that generates the error and that allows for testing the Files.copy () equivalent, both packaged in a zip file.

Q: would it be possible to change the FileBackedOutputStream.update () method implementation to avoid such issue?

**Comment by cpovirk** [comment] 2023-10-06 12:31
Sorry for the trouble. This is caused by the same problem as https://github.com/google/guava/issues/6634. I found a fix last week, but my reviewer ended up out of the office for a little longer than expected, so I reassigned it yesterday. I hope to get it submitted soon. You can follow that other issue for updates.

**Closed by cpovirk** 2023-10-06 12:31 UTC

**Comment by cpovirk** [comment] 2023-10-06 13:35
Oh, I should ask: Are you using Java 8 or some newer version?

**Comment by thebluemountain** [comment] 2023-10-06 15:50
hi,

this is the used  jdk **11.0.16.1** on windows
