### ISSUE TITLE
Eventually require GWT 2.7.0

### ISSUE THREAD

**Issue by cpovirk** [google/guava#1944] opened 2015-01-12 19:25 UTC
(If any of our GWT users are reading here, we'd love to hear about how you handle GWT updates. If you were using a version of Guava released today, how old might the version of GWT you're using with it be?)

Our choice to work with GWT 2.6.1 makes us keep some old code around, e.g., our `Arrays.copyOf` replacements (#1942), our `IteratorTester.stopTestingWhenAddThrowsException` option, and probably other code we don't know about. Someday we'll want to require GWT 2.7.0 and remove the old code. To determine when to do that, we should track what the upgrade would let us accomplish. We can do that here.

Currently, I think that we're best off waiting. We've had reports from users of GWT 2.5.1 a few months ago (see #1824), even though 2.6.0 has been out for just under a year.

**Comment by kluever** [comment] 2015-05-26 17:22
This is a dupe of https://github.com/google/guava/issues/1999 I think.

**Closed by kluever** 2015-05-26 17:22 UTC
Labels: package: general, status: duplicate, status: research, type: dev

**Comment by cgdecker** [comment] 2015-05-26 17:43
(I think it would be the other way around... 1999 is a dupe of 1944. Not that it matters much.)

**Comment by cpovirk** [comment] 2015-05-26 17:48
Heh, whoops. Well, at least I was more thorough in #1999 :)
