### ISSUE TITLE
Remove @Beta from RangeSet and RangeMap

### ISSUE THREAD

**Issue by tyomka** [google/guava#3376] opened 2019-02-06 11:32 UTC
Range has been marked with `@Beta` since 10.0 (September 28, 2011).
RangeMap, RangeSet and their implementations since 14.0 (February 25, 2013). 

I would like to propose to remove the `@Beta` annotation.

**Comment by kevinb9n** [comment] 2019-02-06 23:45
(The only part of Range that's still beta is asSet().)  I feel like we should be able to take care of these in the next batch of debeta-ings.

**Comment by tyomka** [comment] 2019-02-08 14:11
@cpovirk 
I've mistakenly assumed that Range is annotated with `@Beta`. It is not. 
Still the issue context is still relevant for `RangeMap` and `RangeSet`.

**Comment by sd1998** [comment] 2019-07-31 10:22
@tyomka Can I work on this?

**Comment by gskaplan** [comment] 2020-01-17 23:10
Is there any update on this?

**Comment by prissky** [comment] 2020-05-13 11:21
Is there any news?

**Comment by ggarcia-te** [comment] 2020-06-29 19:30
Any news about this?

**Comment by tyomka** [comment] 2020-06-29 21:39
> Any news about this?
I'm kinda waiting for someone from the Guava team to validate my pull request. Is there anything i can?

**Comment by julianhyde** [comment] 2020-09-29 19:24
+1 to remove `@Beta`. Apache Calcite, as of [release 1.26](https://issues.apache.org/jira/browse/CALCITE-4173), relies on `RangeSet` (and it appears in the Calcite's public API in one place, `class Sarg`). We are prepared to shade, and break our API if it comes to that, because `RangeSet` is the perfect library for what we need. Some certainty would be appreciated. If `RangeSet` is going away we can make other plans.

**Comment by zabetak** [comment] 2020-09-30 10:12
I can see that the issue is open for more than a year. Is the Guava team at least considering this request?

**Comment by mwunderlich** [comment] 2021-06-02 06:07
Any updates on removing @Beta for RangeMap (also applies to TreeRangeMap)?

**Comment by runnable-thread** [comment] 2022-01-18 00:07
Any updates on removing @beta for RangeMap (also applies to TreeRangeMap)?

**Comment by kluever** [comment] 2023-04-10 18:44
This is now fixed.

**Closed by kluever** 2023-04-10 18:44 UTC
Labels: package=collect, status=triaged, P3, type=debeta

**Comment by taomoh** [comment] 2023-05-17 17:46
> This is now fixed.

@kluever Do you know which version this fix is going to be released in?
Latest version `31.1-jre` doesn't have it

**Comment by kluever** [comment] 2023-05-17 21:14
It'll be in the next version of Guava --- I think @cpovirk was planning on cutting a release in the next few weeks?

**Comment by cpovirk** [comment] 2023-05-18 14:58
Yes, maybe the end of next week if all goes well. If not, I'd _hope_ the week after.

**Comment by julianhyde** [comment] 2023-05-18 16:35
@cpovirk, It's helpful if you can state the release number when it will be fixed. Because many of us dependent issues and we want to write 'Fixed in Guava 32.0' and move on.

**Comment by cpovirk** [comment] 2023-05-18 17:18
It will be 32.0.0. (Even though it would be a major-version bump, the release will probably not contain any breaking changes to Guava itself: It will just contain a small breaking change to the much less used guava-testlib, and we keep the version numbers of the two in sync.)
