### ISSUE TITLE
Range created with Integers throws ClassCastException when asked if range.contains(Double)

### ISSUE THREAD

**Issue by jcalcote** [google/guava#2821] opened 2017-05-19 16:51 UTC
I realize you have to do something in this scenario, but there's no where I can find in the doc that mentions that users might be interested in watching for a ClassCastException from contains in this situation.

**Comment by lowasser** [comment] 2017-05-19 16:56
`Range<C>.contains` accepts only a `C`.  That means at some point you did an unchecked cast from `Range<Integer>` to `Range<Double>` or the like, no?  And that unchecked cast should've given you a compiler warning telling you about potential ClassCastExceptions.

**Comment by jcalcote** [comment] 2017-05-19 17:00
I never casted in my code - I just called it like this:
Range range = Range.downTo(0);
then later:
range.contains(0.00001);
the call to contains threw a ClassCastException because the range that was created contained a lower bound of type Integer and the value I passed to contains was clearly a Double. When compareTo was used (both are comparable), the code attempted to cast one of them to the other type. As I understand it here, the problem isn't that 0 can't be cast to a double - it's that 0 (integer) can't be autoboxed into a Double.

**Comment by lowasser** [comment] 2017-05-19 17:35
But `Range range = Range.downTo(0)` is still a raw type that should give you a compiler warning: it should complain that Range is a raw type without generic arguments.  The issue is the same as the unchecked cast would be: the compiler should give you a warning that you're risking ClassCastExceptions.  The compiler would want you to write `Range<Integer> range = Range.downTo(0)` and that would reject an attempt to compile `range.contains` on a double.

**Comment by lowasser** [comment] 2017-05-19 17:42
Stepping back: I don't think you can get a ClassCastException here without evading proper generic type checking and getting a compiler warning telling you so.  Raw types and unchecked casts can both produce that result, but they'll both cause compiler warnings telling you you're risking CCEs.

**Comment by jcalcote** [comment] 2017-05-19 17:46
I see what you're saying. I showed you the code I wrote, but I failed to mention that I was calling Range.downTo(minValue, minInclusive) within a generic builder:
```
class GuavaRangeBuilder<T extends Comparable<?>> {
    private T minValue;
    private T maxValue;
    private BoundType minInclusive;
    private BoundType maxInclusive;
    ...
    Range build() {
        ...
        return Range.downTo(minValue, minInclusive);
        ...
}
```
No compiler warnings here - T was an Integer at the time "build()" was called, thus Range was created with an Integer as the lowerBound.

Thanks for the feedback, btw.

**Comment by lowasser** [comment] 2017-05-19 17:48
I would have expected a raw types warning on the line `Range build()` there: shouldn't it require you to write `Range<T> build()`?

**Comment by kluever** [comment] 2017-07-06 17:25
As Louis points out, the raw `Range` type seems to be what's causing the problem. Closing.

**Closed by kluever** 2017-07-06 17:25 UTC
