### ISSUE TITLE
Consider replacing unicode character in Range.toString()

### ISSUE THREAD

**Issue by cowwoc** [google/guava#2376] opened 2016-01-30 01:21 UTC
`Range.toString()` returns `U+2025` which is not supported by the default terminal under Windows, and most IDEs unless you explicitly change the font. If you read through https://issues.apache.org/jira/browse/SUREFIRE-1220 you will understand the insane hoops that developers have to jump through to get this to work.

Consider replacing this unicode character by `..` or `-` or `,` ASCII characters.

**Comment by analog-cbarber** [comment] 2016-02-04 18:57
Yes, gratuitous use of non-ASCII characters in toString() methods is not considerate to users who may not have the right fonts installed. It also results in a string representation that you would never want to actually make users type. Let's say you dump out some ranges in a text config file. How is a user supposed to enter those?

The problem is compounded by the fact that Range is final so you cannot subclass it to work around the problem.

**Comment by kluever** [comment] 2016-02-04 19:41
On an internal thread, @kevinb9n said:

"I regret the error. By this point, though... no telling how many things we'd break by changing it."

**Comment by cowwoc** [comment] 2016-02-04 19:49
> "no telling how many things we'd break by changing it."

If computers are parsing this thing then I think we've got a problem. Pretty much everywhere I've read `Object.toString()` is designed for human consumption, not computer parsing.

**Comment by kluever** [comment] 2016-02-04 19:55
I'm moderately in favor of making this change, so I'm testing the change against google's internal codebase, and will see how much stuff it breaks.

We didn't make the toString() contract explicit, so technically we can change it, but it still make break stuff (imagine if Oracle decided to change the toString() of List...it would definitely break stuff, even though there's no explicit contract).

**Comment by analog-cbarber** [comment] 2016-02-04 20:03
I doubt very many people have written parsers that are explicitly looking for \u2025 or else someone probably would have reported this earlier.

**Comment by lowasser** [comment] 2016-02-04 20:22
A casual search for "\u2025" internally shows a number of people who are totally doing exactly the thing we wish they weren't.

**Comment by kluever** [comment] 2016-02-04 20:34
From some internal code:

>  * {@link Range#toString()} prints a unicode character of \u2025 (two dot leader) between the lower
>  * and upper bound. Neither terminal nor [our internal test tool] prints this character correctly. This is a
>  * workaround.

**Comment by cowwoc** [comment] 2016-02-04 20:48
Hi @lowasser. Can you provide us with some more details? Why are they parsing for `\u2025`? What are they doing with it?

**Comment by lowasser** [comment] 2016-02-04 21:49
@kluever etc. can do that search themselves, but some examples include `range.toString().replace("\u2025", " to ")`, and even worse,

     // string gets passed around, I think through an RPC? 
     String[] range = string.split("\u2025|\\[|\\]");
     return Range.closed(Long.parseLong(range[1]), Long.parseLong(range[2]));

**Comment by analog-cbarber** [comment] 2016-02-04 23:50
If you want to be backward compatible you could always move the separator string in a writable global variable or have a global useASCII variable.

BTW, the same issue exists with the representation of +/- infinity. It would be better to use "Infinity" (which is what Double uses) instead of the magic infinity character.

**Comment by analog-cbarber** [comment] 2016-02-04 23:53
Also, if you add a parse method to Range to read from a String you can have it support the old and new syntax. That would save people from having to write their own parser that explicitly references the separator characters.

**Comment by lowasser** [comment] 2016-02-04 23:55
Mutable global variables are an antipattern the team feels very strongly about avoiding under any circumstances.  We'd definitely prefer the status quo to introducing static state.

As far as parsing goes, that's sort of addressed in #1911 , but generally speaking, there's no general "parsable" interface in Java (nor is such a thing even possible in Java, really?), so we couldn't really support that for Range, since we'd have to also know how to parse the element type.

**Comment by analog-cbarber** [comment] 2016-02-05 00:17
Yes, mutable globals should generally be avoided, but so also should hardcoded non-ASCII characters, so if the alternative is to either break existing code or leave bad behavior, it seems like a reasonable compromise until you can deprecate the old behavior.

As for a parseable interface, something like the Converter API is probably the right thing to do. Users of Java 8 can then use a lambda:

    Range.parseRange(someString, (Double endpoint) -> Double.parseDouble(endpoint));

 You could add a few static methods for integer and double ranges for convenience which would probably cover most user's needs.

**Comment by cowwoc** [comment] 2016-02-05 03:07
A less painful alternative is to add `toString(String separator)` which lets the user override the default separator. No magic globals there. And ideally you would somehow instruct users that the `toString()` implementation will be changing in an upcoming release so if they are somehow tied to a particular separator character they should use `toString(String separator)` instead of `toString()` whose separator may change over time.

As a side-note, I would also point out that it's problematic that `Range` doesn't "know" the underlying element type. See https://github.com/google/guava/issues/2374 for a recent example of how this could lead to misunderstandings.

Would it make sense to supplement `Range` (for `Comparable` in general) with type-specific implementations such as `IntRange`, `LongRange`, etc? It would allow us to implement more intuitive behavior and adding parsing capability because more feasible.

**Comment by kluever** [comment] 2016-02-05 04:54
Internal CL with the change (and cleanups) is 113872392.

Summary:
1 user who is purposefully changing `\u2025` to `", "`
1 user who is purposefully changing `\u2025` to `" to "`
1 user who is calling `String.split("\u2025|\\[|\\]")`, and then doing parsing of the values
15 users who have (somewhat) brittle tests that are expecting exactly `\u2025` in a failure or log message

**Comment by analog-cbarber** [comment] 2016-02-05 14:55
You might want to also look for \u221E (infinity).

An alternate toString implementation should also include a parameter for the infinity representation. It wouldn't hurt to add such a method, but it would be a less than ideal solution to the problem because it would force developers to replace all toString calls including the implicit ones in String.format calls.

**Comment by kluever** [comment] 2016-02-16 20:32
OK, we discussed this at our internal API review, and decided to go ahead with the change to ".." (that is, dot-dot, not the "two dot leader" character).

We may look slightly silly when we have to put this in the release notes for the next Guava release, and we may break some users tests, but hopefully that's the worst of it.

I'm submitting the change internally and it should be mirrored out shortly.

**Comment by cowwoc** [comment] 2016-02-16 21:49
Very nice. Thanks Kurt!

**Closed** 2016-02-17 14:58 UTC
Labels: package: collect, status: fixed, status: research, type: defect
