### ISSUE TITLE
Add guava collection tests for the new collection methods in Java 8

### ISSUE THREAD

**Issue by simonmcooper** [google/guava#2251] opened 2015-12-10 10:59 UTC
There are several significant new collection methods in Java 8 (especially on the Map interface). Tests for these should be added to the guava collection test suite.

**Comment by cpovirk** [comment] 2015-12-10 12:08
Duplicate of #1650, which i can see we haven't updated in a while. I'll do so now.

**Closed by cpovirk** 2015-12-10 12:08 UTC
