### ISSUE TITLE
RateLimiter  is marked unstable with @Beta 

### ISSUE THREAD

**Issue by 2625180201** [google/guava#5959] opened 2022-03-10 09:48 UTC
My compiler shows as below, how should i fix it? use other class?
'com.google.common.util.concurrent.RateLimiter' is marked unstable with @Beta

**Comment by jbduncan** [comment] 2022-03-11 09:33
Depending on if you're in a team that cares about that sort of compiler message, either ignore the message or look into an equivalent library like [resilience4j](https://resilience4j.readme.io/).

**Comment by eamonnmcmanus** [comment] 2022-03-18 18:11
Duplicate of #5612.

**Closed by eamonnmcmanus** 2022-03-18 18:11 UTC
