### ISSUE TITLE
Tree edit distance algorithm support

### ISSUE THREAD

**Issue by Pramodmk** [google/guava#6231] opened 2022-10-28 23:52 UTC
I was looking at the [common.graph](https://github.com/google/guava/tree/master/guava/src/com/google/common/graph) package and the Graphs utility class. I do not see the support for any tree edit distance algorithm which compares two trees. Are there any plans to include such tree features and algorithms ?

**Comment by kevinb9n** [comment] 2022-10-28 23:59
Am not aware of any existing plans.

Generally, the main thing that convinces us to add something to our API is if we can find code in Google's massive internal codebase that would use it. The reasoning is that probably too few people have needed it, or, if Google is just unusual and the rest of the world needs it, well, that doesn't really suggest that *we* are the right people to create and release such a library.

In this case, hmmm. Might be tough to recognize such code... unless perhaps the actual words "edit" and "distance" are mixed in there somewhere. (Or, maybe there are fine patterns to look for; I'm not thinking deeply.)

**Comment by jrtom** [comment] 2022-10-29 02:56
As one of the major contributors to (and primary maintainer of) `common.graph`, I would concur with @kevinb9n that we're unlikely to provide a tree edit distance algorithm:
* I don't recall ever having seen such an algorithm, nor a use case for one.  This isn't conclusive--graph theory is a very broad subject with many different applications, and I don't pretend to be aware of, much less familiar, with all of them--but it does at least suggest that it's not, well, common.
* At this time, `common.graph` does not have a defined `Tree` type.  I'm experimenting with one in a related graph library ([JUNG](https://github.com/jrtom/jung)) but if I understand correctly, tree edit distance isn't meaningful if you don't have a (directed) (rooted) tree (technically an [arborescence](https://en.wikipedia.org/wiki/Arborescence_(graph_theory)) although AFAIK only graph theorists use that term :) ).  Nor do I think it's likely that Guava would adopt such a type soon.
    *  more fundamentally: tree edit distance is usually applied to _ordered_ rooted trees (see below), and that, being a bit more specialized yet, is even less likely to make it into Guava.
        * (yes, we could provide an algorithm for this even without having an explicit type, but not having that type makes this less compelling as a part of Guava.) 
* A brief web search suggests that there's at least a couple of different ways that one can define tree edit distance (depending, for instance, on how you define the 'delete' operation, and on whether you're talking about ordered or unordered trees).  It may be that digging into the literature would indicate that there is a dominant definition, but that fragmentation makes it less likely that we'd invest in this area.
* Finally, a brief literature search suggests that the tree edit distance time complexity is optimally O(n^3) for ordered trees (and that the problem is NP-hard for unordered trees), and space complexity is O(n^2).  This doesn't place it outside the bound of algorithms that we're willing to provide, but it's expensive enough to be discouraging.

Hope this helps.

**Comment by netdpb** [comment] 2022-11-01 15:54
I'm going to close this issue based on the discussion above. If and when we (or you or anyone) makes a compelling case for adding such an algorithm, we can of course reopen this issue to discuss.

**Closed by netdpb** 2022-11-01 15:54 UTC
Labels: type=addition, package=graph
